Black_friday
Niketkumardheeryan/ML-CaPsule pull request #366
Opened 2022-03-25 03:41 UTC by ADITYADAS1999

2022-03-25 04:49 UTC, Rutikab12 requested changes
You have mentioned you used various algorithms, but there is only one algorithm i see there. Please use at least two algorithms.

2022-03-25 05:09 UTC, ADITYADAS1999 commented
> You have mentioned you used various algorithms, but there is only one algorithm i see there. Please use at least two algorithms. Also make a descriptive PR with issue number and other details.

Thank you for response. I recover it asap.

2022-03-27 15:45 UTC, Rutikab12 approved these changes

2022-03-27 15:46 UTC, merged

2022-03-27 15:46 UTC, Rutikab12 commented
You can grab open issues now @ADITYADAS1999